services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../:/workspaces/avion:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - devcontainer
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:16.1-bookworm
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: avion
      POSTGRES_USER: avion
      POSTGRES_DB: avion
    networks:
      - devcontainer

volumes:
  postgres-data:
    driver: local

networks:
  devcontainer:
    driver: bridge
